# Configuration for Ryder Robot Neural Network platform.

# Config for training set 0

networks:
  # Network ID
  - id: "network0"
    success: 0.0004 
    inital_weight: 0.5
    learning_rate: 0.3
    momentum: 0.9

  # input configuration
    input:
      nodes: 7

    # hidden layer(s)
    hidden:
      layers: 2
      nodes: 8
  
    # Output
    output:
      nodes: 4