# Configuration for Ryder Robot Neural Network platform.

# Config for training set 1
#
# Attempts to solve XOR but does it using decimal values.
#
# Currently this test doesn't get past the training stage,  we want to use it because when more sensors get added
# to the robot, we want to send value to the arduino board as floats,  for instance dirive the motor 10, 100 or something like
# that. 

networks:
  # Network ID
  - id: "network0"
    success:  0.0004
    inital_weight: 0.5
    learning_rate: 0.3
    momentum: 0.9

    # Initial training set for network.
    training_set: resources/training/training-set.1.json

  # input configuration
    input:
      nodes: 6

    # hidden layer(s)
    hidden:
      layers: 4
      nodes: 7
  
    # Output
    output:
      nodes: 1

