# Configuration for Ryder Robot Neural Network platform.

# Config for training set 0

networks:
  # Network ID
  - id: "network0"
    success:  0.0004
    inital_weight: 0.5
    learning_rate: 0.3
    momentum: 0.9

    # Initial training set for network.
    training_set: resources/training/training-set.0.json

  # input configuration
    input:
      nodes: 7

    # hidden layer(s)
    hidden:
      layers: 1

      # nodes will be deprecated, there will always be the same number of nodfes as input, plus one
      # more for bias.
      nodes: 8
  
    # Output
    output:
      nodes: 4

